-- Таблица пользовательских взаимодействий
CREATE TABLE IF NOT EXISTS user_interactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action_weight DOUBLE PRECISION NOT NULL,
    last_action_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uk_user_event_interaction UNIQUE (user_id, event_id)
);

-- Таблица коэффициентов сходства мероприятий
CREATE TABLE IF NOT EXISTS event_similarities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a BIGINT NOT NULL,
    event_b BIGINT NOT NULL,
    similarity_score DOUBLE PRECISION NOT NULL,
    calculated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT chk_event_order CHECK (event_a < event_b),
    CONSTRAINT uk_event_pair UNIQUE (event_a, event_b)
);

-- Индексы
CREATE INDEX IF NOT EXISTS idx_user_interactions_user_id ON user_interactions(user_id);
CREATE INDEX IF NOT EXISTS idx_user_interactions_event_id ON user_interactions(event_id);
CREATE INDEX IF NOT EXISTS idx_event_similarities_event_a ON event_similarities(event_a);
CREATE INDEX IF NOT EXISTS idx_event_similarities_event_b ON event_similarities(event_b);
CREATE INDEX IF NOT EXISTS idx_event_similarities_score ON event_similarities(similarity_score DESC);