-- Таблица комментариев (живет в comment-service)
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,     -- Ссылка на событие в event-service
    user_id BIGINT NOT NULL,      -- Ссылка на пользователя в user-service
    text TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PUBLISHED' NOT NULL,

    CONSTRAINT chk_comment_status CHECK (status IN ('PUBLISHED', 'EDITED', 'DELETED')),
    CONSTRAINT chk_comment_text CHECK (LENGTH(TRIM(text)) >= 1 AND LENGTH(text) <= 2000)
    -- ВАЖНО: НЕТ внешних ключей на event_id и user_id
);

-- Индексы для comment-service
CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_event_created ON comments(event_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments(status);
CREATE INDEX IF NOT EXISTS idx_comments_event_status ON comments(event_id, status);

-- Индекс для поиска активных комментариев (не удаленных)
CREATE INDEX IF NOT EXISTS idx_comments_event_active
ON comments(event_id, created_at DESC)
WHERE status IN ('PUBLISHED', 'EDITED');