-- user-service/src/main/resources/schema.sql
CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250)        NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL,

    CONSTRAINT chk_user_name_length CHECK (LENGTH(name) >= 2),
    CONSTRAINT chk_user_email_length CHECK (LENGTH(email) >= 6)
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_name ON users(name);