-- Таблица заявок на участие (живет в request-service)
CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT NOT NULL, -- Ссылка на пользователя в user-service
    event_id BIGINT NOT NULL,     -- Ссылка на событие в event-service
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED'))
    -- ВАЖНО: НЕТ внешних ключей на requester_id и event_id
);

-- Индексы для request-service
CREATE INDEX IF NOT EXISTS idx_requests_requester_id ON participation_requests(requester_id);
CREATE INDEX IF NOT EXISTS idx_requests_event_id ON participation_requests(event_id);
CREATE INDEX IF NOT EXISTS idx_requests_event_status ON participation_requests(event_id, status);
CREATE INDEX IF NOT EXISTS idx_requests_created_at ON participation_requests(created_at);
CREATE INDEX IF NOT EXISTS idx_requests_requester_event ON participation_requests(requester_id, event_id);

-- Уникальный индекс для предотвращения дублирования заявок (как в бизнес-логике)
CREATE UNIQUE INDEX IF NOT EXISTS uk_requests_requester_event
ON participation_requests(requester_id, event_id)
WHERE status NOT IN ('CANCELED', 'REJECTED');