-- Таблица категорий (живет в event-service)
CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,

    CONSTRAINT chk_categories_name_length CHECK (LENGTH(name) >= 1)
);

-- Таблица событий (живет в event-service)
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    description TEXT,
    category_id BIGINT NOT NULL,
    initiator_id BIGINT NOT NULL, -- Ссылка на пользователя в user-service
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    location_lat DOUBLE PRECISION NOT NULL,
    location_lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    participant_limit INT DEFAULT 0,
    request_moderation BOOLEAN DEFAULT TRUE,
    state VARCHAR(20) NOT NULL,

    CONSTRAINT chk_state CHECK (state IN ('PENDING', 'PUBLISHED', 'CANCELED'))
    -- ВАЖНО: НЕТ внешних ключей на category_id и initiator_id
);

-- Таблица подборок (живет в event-service)
CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title  VARCHAR(55) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE NOT NULL
);

-- Связующая таблица для подборок (many-to-many)
CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,

    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_compilation_compilation FOREIGN KEY (compilation_id)
        REFERENCES compilations (id) ON DELETE CASCADE
    -- ВАЖНО: НЕТ внешнего ключа на event_id (ссылается на таблицу в этом же сервисе)
);

-- Индексы для event-service
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_published_on ON events(published_on);
CREATE INDEX IF NOT EXISTS idx_compilations_pinned ON compilations(pinned);
CREATE INDEX IF NOT EXISTS idx_compilation_events_event ON compilation_events(event_id);